profiles: dev
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/guide?useUnicode=true&amp;characterEncoding=UTF8
    driver-class-name: com.mysql.jdbc.Driver
    password: 1234
    username: root
  jpa:
    show-sql: true

logging:
  level:
    com.straw.guide.mapper: DEBUG
debug: true